// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int32
	Name      string
	Phone     string
	Password  string
	Status    pgtype.Text
	CreatedAt pgtype.Timestamptz
}
