// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID        int32
	LeadID    int32
	UserID    int32
	UpdatedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Lead struct {
	ID        int32
	Name      pgtype.Text
	Address   pgtype.Text
	Phone     string
	Completed bool
	UserID    pgtype.Int4
	SaleID    pgtype.Int4
	CreatedAt pgtype.Timestamptz
	SoldAt    pgtype.Timestamptz
}

type LeadWh struct {
	ID        int32
	Name      string
	Phone     string
	Jid       pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type Message struct {
	ID          int32
	Text        pgtype.Text
	Path        pgtype.Text
	Type        string
	IsSent      bool
	AudioLength int32
	ChatID      int32
	CreatedAt   pgtype.Timestamptz
}

type Product struct {
	ID         int32
	Name       string
	InStock    int32
	Price      int32
	SaleCount  int32
	StockPrice int32
	CreatedAt  pgtype.Timestamptz
}

type ProductChange struct {
	ID        int32
	Quantity  int32
	IsIncome  bool
	ProductID int32
	CreatedAt pgtype.Timestamptz
}

type Report struct {
	ID        int32
	Name      string
	Path      string
	StartAt   pgtype.Timestamptz
	EndAt     pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Sale struct {
	ID           int32
	Type         string
	DeliveryType pgtype.Text
	PaymentAt    pgtype.Timestamptz
	FullSum      float32
	DeliveryCost float32
	LoanCost     float32
	ItemsSum     float32
	CreatedAt    pgtype.Timestamptz
}

type SaleItem struct {
	ID          int32
	Price       float32
	ProductName string
	SaleCount   int32
	Quantity    int32
	SaleID      int32
	ProductID   int32
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID        int32
	Name      string
	Phone     string
	Password  string
	Role      string
	Jid       pgtype.Text
	CreatedAt pgtype.Timestamptz
}
