// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID         int32
	Name       string
	InStock    int32
	Price      int32
	StockPrice int32
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID        int32
	Name      string
	Phone     string
	Password  string
	Role      string
	Active    bool
	CreatedAt pgtype.Timestamptz
}
