// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: products.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addStockProduct = `-- name: AddStockProduct :one
UPDATE products
SET in_stock = in_stock + $2
WHERE id = $1
RETURNING in_stock
`

type AddStockProductParams struct {
	ID      int32
	InStock int32
}

func (q *Queries) AddStockProduct(ctx context.Context, arg AddStockProductParams) (int32, error) {
	row := q.db.QueryRow(ctx, addStockProduct, arg.ID, arg.InStock)
	var in_stock int32
	err := row.Scan(&in_stock)
	return in_stock, err
}

const deleteProduct = `-- name: DeleteProduct :one
DELETE FROM products
WHERE id = $1
RETURNING id, name, in_stock, price, sale_count, stock_price, created_at
`

func (q *Queries) DeleteProduct(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, deleteProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InStock,
		&i.Price,
		&i.SaleCount,
		&i.StockPrice,
		&i.CreatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, in_stock, price, sale_count, stock_price, created_at FROM products 
WHERE id = $1 
LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InStock,
		&i.Price,
		&i.SaleCount,
		&i.StockPrice,
		&i.CreatedAt,
	)
	return i, err
}

const getProductByName = `-- name: GetProductByName :one
SELECT id, name, in_stock, price, sale_count, stock_price, created_at FROM products
WHERE name = $1 
LIMIT 1
`

func (q *Queries) GetProductByName(ctx context.Context, name string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByName, name)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InStock,
		&i.Price,
		&i.SaleCount,
		&i.StockPrice,
		&i.CreatedAt,
	)
	return i, err
}

const getProductChanges = `-- name: GetProductChanges :many
SELECT id, quantity, is_income, product_id, created_at FROM product_changes
WHERE created_at > $1 AND created_at < $2
ORDER BY created_at ASC
`

type GetProductChangesParams struct {
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

func (q *Queries) GetProductChanges(ctx context.Context, arg GetProductChangesParams) ([]ProductChange, error) {
	rows, err := q.db.Query(ctx, getProductChanges, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductChange
	for rows.Next() {
		var i ProductChange
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.IsIncome,
			&i.ProductID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProducts = `-- name: GetProducts :many
SELECT id, name, in_stock, price, sale_count, stock_price, created_at FROM products 
ORDER BY created_at DESC 
LIMIT $2 
OFFSET $1
`

type GetProductsParams struct {
	Offset int64
	Limit  int64
}

func (q *Queries) GetProducts(ctx context.Context, arg GetProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProducts, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InStock,
			&i.Price,
			&i.SaleCount,
			&i.StockPrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsCount = `-- name: GetProductsCount :one
SELECT COUNT(*) 
FROM products
`

func (q *Queries) GetProductsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getProductsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products(name, in_stock, price, sale_count, stock_price)
VALUES($1, $2, $3, $4, $5)
RETURNING id, name, in_stock, price, sale_count, stock_price, created_at
`

type InsertProductParams struct {
	Name       string
	InStock    int32
	Price      int32
	SaleCount  int32
	StockPrice int32
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, insertProduct,
		arg.Name,
		arg.InStock,
		arg.Price,
		arg.SaleCount,
		arg.StockPrice,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InStock,
		&i.Price,
		&i.SaleCount,
		&i.StockPrice,
		&i.CreatedAt,
	)
	return i, err
}

const insertProductChange = `-- name: InsertProductChange :one
INSERT INTO product_changes(quantity, is_income, product_id)
VALUES($1 ,$2 , $3)
RETURNING id, quantity, is_income, product_id, created_at
`

type InsertProductChangeParams struct {
	Quantity  int32
	IsIncome  bool
	ProductID int32
}

func (q *Queries) InsertProductChange(ctx context.Context, arg InsertProductChangeParams) (ProductChange, error) {
	row := q.db.QueryRow(ctx, insertProductChange, arg.Quantity, arg.IsIncome, arg.ProductID)
	var i ProductChange
	err := row.Scan(
		&i.ID,
		&i.Quantity,
		&i.IsIncome,
		&i.ProductID,
		&i.CreatedAt,
	)
	return i, err
}

const removeStockProduct = `-- name: RemoveStockProduct :one
UPDATE products
SET in_stock = in_stock - $2
WHERE id = $1
RETURNING in_stock
`

type RemoveStockProductParams struct {
	ID      int32
	InStock int32
}

func (q *Queries) RemoveStockProduct(ctx context.Context, arg RemoveStockProductParams) (int32, error) {
	row := q.db.QueryRow(ctx, removeStockProduct, arg.ID, arg.InStock)
	var in_stock int32
	err := row.Scan(&in_stock)
	return in_stock, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2, price = $3, stock_price = $4, sale_count = $5
WHERE id = $1
RETURNING id, name, in_stock, price, sale_count, stock_price, created_at
`

type UpdateProductParams struct {
	ID         int32
	Name       string
	Price      int32
	StockPrice int32
	SaleCount  int32
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.StockPrice,
		arg.SaleCount,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InStock,
		&i.Price,
		&i.SaleCount,
		&i.StockPrice,
		&i.CreatedAt,
	)
	return i, err
}
