CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	phone VARCHAR(15) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	status VARCHAR(20) DEFAULT 'active',
	created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
