name: Building and testing
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
      - name: Install dependencies
        run: |
          echo 'hello'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Setup SSH
        run: |
          echo 'hello'
      - name: Deploy to server
        run: |
          echo 'hello'
