name: Building and testing
on: push

jobs:
  name: Build and test
  runs_on: ubuntu-latest

  steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Golang
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.2
    - name: Install dependencies
      run: |
        curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
        chmod +x tailwindcss-linux-x64
        mv tailwindcss-linux-x64 tailwindcss
        mkdir logs
        make
