# name: Building and testing
# on: 
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Clone repository
#         uses: actions/checkout@v4
#       - name: Set up Golang
#         uses: actions/setup-go@v5
#         with:
#           go-version: 1.22.2
#       - name: Install dependencies
#         run: |
#           curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
#           chmod +x tailwindcss-linux-x64
#           mv tailwindcss-linux-x64 tailwindcss
#           mkdir logs
#           make
#   deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     steps:
#       - name: Clone repo
#         uses: actions/checkout@v4
#       - name: Setup SSH
#         run: |
#           echo "${{ secrets.SSH_PRIVATE_KEY }}" > main.pem
#           chmod 600 main.pem
#       - name: Deploy to server
#         run: |
#           ssh -i "main.pem" -o StrictHostKeyChecking=no ${{ secrets.ALAMAN_HOST }} << 'EOF'
#           cd alaman
#           git pull origin main
#           make
#           pkill -f "sudo ./server" || true
#           nohup sudo ./server > /dev/null 2>&1 &
#           exit
#           EOF
